# Introduzione

Nel presente lavoro viene proposta la valutazione in termini di accuratezza di svariati algoritmi di clustering, effettuati sulla rete conosciuta come "Human Disease Network" (HDN [-@hdn]).\newline
La rete in questione contiene nodi che rappresentano malattie e nodi di espressione genica, che sono così collegati:
\begin{itemize}
\item Malattia-Gene: se la mutazione del gene causa la malattia
\item Malattia-Malattia: se vi è almeno un gene condiviso
\end{itemize}
L'obiettivo di studio su questa rete è quello di verificare la presenza di distinti moduli funzionali di espressione genica, che vanno ad influenzare un certo tipo di malattia. I ricercatori hanno dimostrato che alcuni geni tendono a raggrupparsi in moduli ben distinti, ma anche che molti di essi non lo fanno e tendono invece a isolarsi in zone periferiche della rete. \newline
I ricercatori hanno manualmente etichettato ogni nodo, scegliendo tra 22 cluster che rappresentano il sistema fisiologico colpito dalla malattia, permettendo quindi di avere una groundtruth su cui effettuare delle valutazioni. \newline
Basandosi sulle ipotesi effettuate in precedenza, sono riusciti a dimostrare come alcuni di questi cluster si trovino effettivamente vicini e ben connessi all'interno della rete (Es. i nodi relativi al cancro condividono un enorme numero di geni), mentre altri cluster sono sparsi per tutta la rete e quindi difficilmente classificabili utilizzando approcci automatici di partizionamento.\newline
L'obiettivo del lavoro è stato quindi quello di valutare le performance di vari algoritmi di \textit{graph partitioning} e \textit{community detection}, nel rilevare i cluster all'interno della rete, utilizzando principalmente approcci non supervisionati e semi-supervisionati.
