# Network analysis

## Operazioni preliminari
```{r message=FALSE, warning=FALSE}
# set working directory
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
# source a set of functions
source("util.R")

# import libraries
libraries_list <- c("ggraph", "igraph", "dplyr", "readr", "DiagrammeR", "tidyverse", "Cairo", "networkD3", "CINNA", "scales")
import_libraries(libraries_list)
```

```{r graph}
# import graph
edges <- read.csv(
  "../dataset/diseasome [Edges].csv",
  head = TRUE
)

nodes <- read.csv(
  "../dataset/diseasome [Nodes].csv",
  head = TRUE
)

nodes <- nodes %>% select(-timeset)
edges <- edges %>% select(-timeset, -label)

graph <- graph.data.frame(edges, directed = TRUE, vertices = nodes)
# print(graph, e=TRUE, v=TRUE) ## IGRAPH 9af20f4 DNW- 1419 3926

ggraph(graph, layout = 'kk') +
  geom_edge_fan(colour = "gray") + 
  geom_node_point() +
  theme_graph(base_family = "sans", base_size = 11) +
  ggtitle("Human Disease Network")
```
```{r}
vcount(graph)
ecount(graph)
```


```{r edge_similarity}
# similarities
ggplot(edges, aes(x = edges$Source, y = edges$Target, color = "red")) + 
  geom_point() + 
  labs(x = "Source") +
  labs(y = "Target") +
  ggtitle("Edges similarity")

# no isolated nodes
```


## Centrality Analitycs

### Degree

```{r degree_histogram}
degree <- centr_degree(graph, mode = "all", normalized = TRUE)

ggplot(mapping=aes(degree$res)) + 
  geom_histogram(col="black", fill="red") + 
  scale_y_log10(labels = trans_format("log10", math_format(expr = 10^.x))) +
  scale_x_continuous(breaks = seq(0, 160, by = 20)) +
  labs(x = "degree") +
  labs(y = "frequency") +
  ggtitle("Degree histogram") +
  theme_bw()
```


```{r graph_degree}
ggraph(graph, layout = 'kk') +
  geom_edge_fan(colour = "gray") +
  geom_node_point(aes(size = degree$res, colour=degree$res)) + 
  labs(size="degree", colour="degree") +
  theme_graph(base_size = 11, base_family = "sans") +
  ggtitle("Human Disease Network Degree Centrality") 

# node with the higest degree
V(graph)$label[degree$res==max(degree$res)] # "Colon cancer"
```

### Betweenness

```{r betweennes_histogram}
betweenness <- betweenness(graph, v = V(graph), directed = TRUE, normalized = TRUE)

ggplot(mapping=aes(betweenness)) + 
  geom_histogram(col="black", fill="red") + 
  scale_y_log10(labels = trans_format("log10", math_format(expr = 10^.x))) +
  scale_x_continuous(limits = c(0, 1)) +
  labs(x = "betweenness") +
  labs(y = "frequency") +
  ggtitle("Betweenness histogram") +
  theme_bw()
```

```{r graph_betweennes}
ggraph(graph, layout = 'kk') + 
  geom_edge_fan(colour = "gray") + 
  geom_node_point(aes(size = ifelse(betweenness > .08, 20, betweenness+5), colour = betweenness)) +
  theme_graph(base_family = "sans", base_size = 11) +
  #geom_node_label(aes(label = ifelse(betweenness > .12, levels(nodes$label), NA), size = 2)) +
  labs(size="betweenness", col="betweenness") +
  ggtitle("Human Disease Network Betweenness Centrality") 

# node with the higest betweenness
V(graph)$label[betweenness==max(betweenness)] # "Cardiomyopathy"
```

### Closeness

```{r closeness_histogram}
closeness <- closeness(graph, v = V(graph), normalized = TRUE)

ggplot(mapping=aes(closeness)) + 
  geom_histogram(col="black", fill="red") + 
  scale_y_log10(labels = trans_format("log10", math_format(expr = 10^.x))) +
  scale_x_continuous(limits = c(0, 1)) +
  labs(x = "closeness") +
  labs(y = "frequency") +
  ggtitle("Closeness histogram") +
  theme_bw()
```

```{r graph_closeness}
ggraph(graph, layout = 'kk') + 
  geom_edge_fan(colour = "gray") + 
  geom_node_point(aes(size = closeness)) +
  theme_graph(base_family = "sans", base_size = 11) +
  ggtitle("Human Disease Network Closeness Centrality") 

# node with the higest closeness
V(graph)$label[closeness==max(closeness)] # "Lipodystrophy"
```

### Pagerank
```{r pagerank_histogram}
pagerank <- page_rank(graph, v = V(graph), directed = TRUE)

ggplot(mapping=aes(pagerank$vector)) + 
  geom_histogram(col="black", fill="red") + 
  scale_y_log10(labels = trans_format("log10", math_format(expr = 10^.x))) +
  #scale_x_continuous(limits = c(0, 1)) +
  labs(x = "pagerank") +
  labs(y = "frequency") +
  ggtitle("Pagerank histogram") +
  theme_bw()
```

```{r graph_pagerank}
ggraph(graph, layout = 'kk') +
  geom_edge_fan(colour = "gray") +
  geom_node_point(aes(size = pagerank$vector)) +
  theme_graph(base_family = "sans", base_size = 11) +
  labs(size="pagerank") +
  ggtitle("Human Disease Network Pagerank Centrality") 

# node with the higest pagerank
V(graph)$label[pagerank$vector==max(pagerank$vector)] # "Colon cancer"
```

### Eigenvector

```{r eigen_histogram}
eigen <- eigen_centrality(graph, directed = TRUE)

ggplot(mapping=aes(eigen$vector)) + 
  geom_histogram(col="black", fill="red") + 
  scale_y_log10(labels = trans_format("log10", math_format(expr = 10^.x))) +
  scale_x_continuous(limits = c(0, 1)) +
  labs(x = "eigen") +
  labs(y = "frequency") +
  ggtitle("Eigenvector histogram") +
  theme_bw()
```

```{r graph_eigen}
ggraph(graph, layout = 'kk') +
  geom_edge_fan(colour = "gray") +
  geom_node_point(aes(size = eigen$vector)) +
  theme_graph(base_family = "sans", base_size = 11) +
  labs(size="eigenvector") +
  ggtitle("Human Disease Network Eigenvector Centrality") 

# node with the higest eigen
V(graph)$label[eigen$vector==max(eigen$vector)] # "Colon cancer"
```

## Network without genes and weighted

Settiamo il peso di ogni arco pari al numero di geni che condividono le malattie:

```{r}
for (i in 1:length(edges[, 5]))
{
  edge <- edges[i, ]
  
  n1 <- V(graph)[as.character(edge$Source)]
  n2 <- V(graph)[as.character(edge$Target)]
  
  # find the vertices not farther than a given limit from another fixed vertex  
  n1.neigh <- neighborhood(graph, nodes = n1)[[1]]
  n2.neigh <- neighborhood(graph, nodes = n2)[[1]]
  
  n1.neigh <- as.numeric(n1.neigh[n1.neigh$X1 == "gene"])
  n2.neigh <- as.numeric(n2.neigh[n2.neigh$X1 == "gene"])
  
  weight <- length(intersect(n1.neigh, n2.neigh))
  
  edges[i, ]$weight <- weight
}

weighted_graph <- graph.data.frame(edges, directed = FALSE, vertices = nodes)


UD_nogenes <- induced_subgraph(weighted_graph, which(nodes$X1 != "gene"))

# Rimuovo i doppi nodi
UD_nogenes <- igraph::simplify(UD_nogenes)

ggraph(UD_nogenes, layout = 'kk') +
  geom_edge_fan(colour = "gray") + 
  geom_node_point() +
  theme_graph(base_family = "sans", base_size = 11) +
  ggtitle("Human Disease Network")
```
```{r}
vcount(UD_nogenes)
ecount(UD_nogenes)
```
## Centrality Analitycs

### Degree

```{r UD_nogenes_degree_histogram}
UD_nogenes_degree <- centr_degree(UD_nogenes, mode = "all", normalized = TRUE)

ggplot(mapping=aes(UD_nogenes_degree$res)) + 
  geom_histogram(col="black", fill="red") + 
  scale_y_log10(labels = trans_format("log10", math_format(expr = 10^.x))) +
  scale_x_continuous(breaks = seq(0, 160, by = 20)) +
  labs(x = "degree") +
  labs(y = "frequency") +
  ggtitle("Degree histogram (nogenes)") +
  theme_bw()
```
```{r}
plot_graph <- function(graph, layout, measure, edge_width, node_s1, node_s2, node_s3, label, label_s1, title){
  ggraph(graph, layout=layout) + #  "graphopt""
  geom_edge_fan(aes(width=edge_width), colour = "gray66", show.legend = FALSE) +
  geom_node_point(aes(fill=nodes$X1[nodes$X0 == "disease"],
                      size=ifelse(measure > node_s1, 30,
                           ifelse(measure > node_s2,  8, 
                           ifelse(measure > node_s3,  3, 1)))),
                      shape=21, col="grey25", show.legend = FALSE) +
  geom_node_text(aes(label = ifelse(measure > label_s1, 
                                    as.character(label), NA), size=2), 
                 show.legend = FALSE) +
  #labs(size="indegree", fill="cluster") +
  scale_edge_width_continuous(range=c(0.2,0.9)) +
  scale_size_continuous(range=c(1, 10)) +
  theme_graph(base_size = 11, base_family = "sans") +
  ggtitle(title) 
}
```

```{r UD_nogenes_degree}
plot_graph(UD_nogenes, "dh", UD_nogenes_degree$res, E(UD_nogenes)$weight, 25, 15, 8, nodes$label[nodes$X0 == "disease"], 25, "Human Disease Network (nogenes) Degree Centrality")

# node with the higest degree
V(UD_nogenes)$label[UD_nogenes_degree$res==max(UD_nogenes_degree$res)] # "Colon cancer"
```
### Betweenness

```{r UD_nogenes_betweennes_histogram}
UD_nogenes_betweenness <- betweenness(UD_nogenes, v = V(UD_nogenes), directed = TRUE, normalized = TRUE, weights=E(UD_nogenes)$weight)

ggplot(mapping=aes(UD_nogenes_betweenness)) + 
  geom_histogram(col="black", fill="red") + 
  scale_y_log10(labels = trans_format("log10", math_format(expr = 10^.x))) +
  scale_x_continuous(limits = c(0, 1)) +
  labs(x = "betweenness") +
  labs(y = "frequency") +
  ggtitle("Betweenness histogram (nogenes)") +
  theme_bw()
```

```{r UD_nogenes_UD_nogenes_betweennes}
plot_graph(UD_nogenes, "dh", UD_nogenes_betweenness, E(UD_nogenes)$weight, 0.3, 0.1, 0.005, nodes$label[nodes$X0 == "disease"], 0.3, "Human Disease Network (nogenes) Betweenness Centrality")

# node with the higest betweenness
V(UD_nogenes)$label[UD_nogenes_betweenness==max(UD_nogenes_betweenness)] # "Cardiomyopathy"
```

### Closeness

```{r UD_nogenes_closeness_histogram}
UD_nogenes_closeness <- closeness(UD_nogenes, v = V(UD_nogenes), normalized = TRUE, weights=E(UD_nogenes)$weight)

ggplot(mapping=aes(UD_nogenes_closeness)) + 
  geom_histogram(col="black", fill="red") + 
  scale_y_log10(labels = trans_format("log10", math_format(expr = 10^.x))) +
  scale_x_continuous(limits = c(0, 1)) +
  labs(x = "closeness") +
  labs(y = "frequency") +
  ggtitle("Closeness histogram (nogenes)") +
  theme_bw()
```

```{r UD_nogenes_closeness}
ggraph(UD_nogenes, layout = 'kk') + 
  geom_edge_fan(colour = "gray") + 
  geom_node_point(aes(size = UD_nogenes_closeness)) +
  theme_graph(base_family = "sans", base_size = 11) +
  ggtitle("Human Disease Network (nogenes) Closeness Centrality") 

# node with the higest closeness
V(UD_nogenes)$label[UD_nogenes_closeness==max(UD_nogenes_closeness)] # "Lipodystrophy"
```

### Pagerank
```{r UD_nogenes_pagerank_histogram}
UD_nogenes_pagerank <- page_rank(UD_nogenes, v = V(UD_nogenes), directed = TRUE, weights=E(UD_nogenes)$weight)

ggplot(mapping=aes(UD_nogenes_pagerank$vector)) + 
  geom_histogram(col="black", fill="red") + 
  scale_y_log10(labels = trans_format("log10", math_format(expr = 10^.x))) +
  #scale_x_continuous(limits = c(0, 1)) +
  labs(x = "pagerank") +
  labs(y = "frequency") +
  ggtitle("Pagerank histogram (nogenes)") +
  theme_bw()
```

```{r UD_nogenes_pagerank}
plot_graph(UD_nogenes, "dh", UD_nogenes_pagerank$vector, E(UD_nogenes)$weight, 0.01, 0.0025, 0.0008, nodes$label[nodes$X0 == "disease"], 0.01, "Human Disease Network (nogenes) Pagerank Centrality")

# node with the higest pagerank
V(UD_nogenes)$label[UD_nogenes_pagerank$vector==max(UD_nogenes_pagerank$vector)] # "Colon cancer"
```

### Eigenvector

```{r UD_nogenes_eigen_histogram}
UD_nogenes_eigen <- eigen_centrality(UD_nogenes, directed = TRUE, weights=E(UD_nogenes)$weight)

ggplot(mapping=aes(UD_nogenes_eigen$vector)) + 
  geom_histogram(col="black", fill="red") + 
  scale_y_log10(labels = trans_format("log10", math_format(expr = 10^.x))) +
  scale_x_continuous(limits = c(0, 1)) +
  labs(x = "eigen") +
  labs(y = "frequency") +
  ggtitle("Eigenvector histogram (nogenes)") +
  theme_bw()
```

```{r UD_nogenes_eigen}
plot_graph(UD_nogenes, "dh", UD_nogenes_eigen$vector, E(UD_nogenes)$weight, 0.9, 0.04, 0.01, nodes$label[nodes$X0 == "disease"], 0.9, "Human Disease Network (nogenes) Eigenvector Centrality")

# node with the higest eigen
V(UD_nogenes)$label[UD_nogenes_eigen$vector==max(UD_nogenes_eigen$vector)] # "Colon cancer"
```
#### Dendogramma

```{r}
dendrogram <- as.dendrogram(hclust(dist(UD_nogenes[,])))
ggraph(dendrogram, 'dendrogram') + 
  geom_edge_diagonal() +
  ggtitle("Human Disease Network (nogenes) dendogram") 
```
