# Clustering

```{r message=FALSE, warning=FALSE, include=FALSE}
# source a set of functions
source("util.R")

# import libraries
libraries_list <- c("ggraph", "igraph", "dplyr", "readr", "DiagrammeR", "tidyverse", "Cairo", "networkD3", "CINNA", "scales", "gridExtra")
import_libraries(libraries_list)

# import graph
edges <- read.csv(
  "../dataset/diseasome [Edges].csv",
  head = TRUE
)

nodes <- read.csv(
  "../dataset/diseasome [Nodes].csv",
  head = TRUE
)

nodes <- nodes %>% select(-timeset)
edges <- edges %>% select(-timeset, -label)

graph <- graph.data.frame(edges, directed = FALSE, vertices = nodes)
# print(graph, e=TRUE, v=TRUE) ## IGRAPH 9af20f4 DNW- 1419 3926
```

Settiamo il peso di ogni arco pari al numero di geni che condividono le malattie:
```{r}
for (i in 1:length(edges[, 5]))
{
  edge <- edges[i, ]
  
  n1 <- V(graph)[as.character(edge$Source)]
  n2 <- V(graph)[as.character(edge$Target)]
  
  n1.neigh <- neighborhood(graph, nodes = n1)[[1]]
  n2.neigh <- neighborhood(graph, nodes = n2)[[1]]
  
  n1.neigh <- as.numeric(n1.neigh[n1.neigh$X1 == "gene"])
  n2.neigh <- as.numeric(n2.neigh[n2.neigh$X1 == "gene"])
  
  weight <- length(intersect(n1.neigh, n2.neigh))
  
  edges[i, ]$weight <- weight
}

graph <- graph.data.frame(edges, directed = FALSE, vertices = nodes)
```

Le malattie sono già clusterizzate in macrogruppi medici (cancro, cardiovascolare, etc...), proviamo a vedere se questi cluster si trovano vicini all'interno della rete:
```{r}
UD_nogenes <- induced_subgraph(graph, which(nodes$X1 != "gene"))

# Rimuovo i doppi nodi
UD_nogenes <- igraph::simplify(UD_nogenes)

disease_clusters <- unique(nodes$X1)

i = 1
for (disease in disease_clusters)
{
  V(UD_nogenes)[V(UD_nogenes)$X1 == disease]$color = i
  i = i + 1
}

ggraph(UD_nogenes, layout = "kk") +
  geom_edge_fan(colour = "gray", show.legend = TRUE) + 
  geom_node_point(colour = V(UD_nogenes)$color) +
  theme_graph(base_family = "sans", base_size = 11) +
  ggtitle("Human Disease Network Clusters")
```

```{r}

graphs <- NULL
plots <- NULL
i <- 1

for (disease in disease_clusters)
{
  if (disease == "gene")
    next
    
  graphs[[i]] <- induced.subgraph(nogenes, which(V(nogenes)$X1 == disease))
  
  if (disease %in% c("Unclassified", "Respiratory"))
  {
    plots[[i]] <- ggraph(graphs[[i]], layout = "kk") +
      geom_node_point() +
      theme_graph(base_family = "sans", base_size = 11) +
      ggtitle(disease)
  } else
  {
    plots[[i]] <- ggraph(graphs[[i]], layout = "kk") +
      geom_edge_fan(colour = "gray", show.legend = TRUE) +
      geom_node_point(colour = "red") +
      theme_graph(base_family = "sans", base_size = 11) +
      ggtitle(disease)
  }
  
  i = i + 1

}

# grid.arrange(grobs = plots)
```

Vediamo quante componenti connesse abbiamo per ogni cluster:
```{r}

n.cluster <- 0

for (g in graphs)
{
  component <- components(g)
  n.cluster = n.cluster + length(component[component$csize > 8]$csize)
}

print(n.cluster)
```

```{r}
UD_graph <- graph.data.frame(edges, directed = FALSE, vertices = nodes)

UD_nogenes <- induced_subgraph(UD_graph, which(nodes$X1 != "gene"))

# Rimuovo i doppi nodi
UD_nogenes <- igraph::simplify(UD_nogenes)

betwennes.communities <- edge.betweenness.community(UD_nogenes, directed = FALSE, weights = E(UD_nogenes)$weight)

V(UD_nogenes)[betwennes.communities[[2]]]$X1
```

```{r}
fgreedy.communities <- fastgreedy.community(UD_nogenes, modularity = TRUE, weights = E(UD_nogenes)$weight)

V(UD_nogenes)[fgreedy.communities[[5]]]$X1
```

```{r}
UD_louvain <- cluster_louvain(UD_nogenes)

#plot(UD_graph, vertex.color=rainbow(26, alpha=0.6)[UD_louvain$membership], vertex.label=NA, vertex.size=5)

ggraph(UD_nogenes, layout = 'kk') +
  geom_edge_fan(colour = "gray") + 
  geom_node_point(colour = UD_louvain$membership) +
  theme_graph(base_family = "sans", base_size = 11) +
  ggtitle("Human Disease Network Louvain Membership")

```

```{r}
UD_springlass <- cluster_spinglass(UD_nogenes, spins = 225)


ggraph(UD_nogenes, layout = 'kk') +
  geom_edge_fan(colour = "gray") + 
  geom_node_point(colour = UD_springlass$membership) +
  theme_graph(base_family = "sans", base_size = 11) +
  ggtitle("Human Disease Network Louvain Membership")
```

```{r}

library(MCL)

adjmat <- as_adj(nogenes, type = "both")

mcl_clusters <- mcl(adjmat, addLoops = TRUE)

ggraph(graph, layout = 'kk') +
  geom_edge_fan(colour = "gray") + 
  geom_node_point(aes(colour = mcl_clusters$Cluster)) +
  scale_color_gradientn(colours = rainbow(5)) +
  theme_graph(base_family = "sans", base_size = 11) +
  ggtitle("Human Disease Network Louvain Membership")
```