# Conclusioni

Dalle prime valutazioni effettuate sulla rete, avevamo subito capito che il compito di clusterizzare automaticamente le varie malattie all'interno della rete sarebbe stato particolarmente arduo. \newline
Dei 22 gruppi di malattie meno della metà presentava componenti connesse di buone dimensioni, mentre la maggior parte delle malattie non avevano vicini che condividevano lo stesso cluster, oppure ne avevano un numero particolarmente basso. \newline
Non avendo a disposizione feature, escluso il peso tra i nodi, non è stato possibile procedere con l'utilizzo di tecniche standard, ma è stato necessario adottare tecniche di community detection. Queste tecniche sono pensate per trovare regioni ben connesse all'interno della rete e ciò va in controtendenza con le valutazioni iniziali. \newline
Con queste premesse possiamo considerare positivamente i risultati raggiunti, gli algoritmi più classici di community detection basati sulla massimizzazione della modularità falliscono in quanto non sono in grado di rilevare cluster di piccole dimensioni; al contrario gli algoritmi come Leiden o MCL hanno prestazioni superiori poichè sono in grado di rilevare un grande numero di community grazie al tuning di parametri interni. \newline
La scelta di algoritmi non ottimali è stata principalmente dettata dalla mancanza di soluzioni alternative; in letteratura sono presenti numerosi algoritmi, anche molto recenti, più incentrati sul graph partitioning/clustering che sulla community detection, ma la mancanza di implementazioni utili li rende praticamente impossibili da testare. L'algoritmo Leiden (2018) è stato l'unico algoritmo recente che sia stato implementato in R ed è infatti quello che ottiene performance decisamente superiori rispetto agli altri. \newline
In futuro sarebbe interessante l'implementazione e la valutazione di questi algoritmi, ma soprattutto l'integrazione con altre fonti di dati per ottenere, per esempio, relazioni intra-geniche utilizzabili come feature set per la clusterizzazione. \newline
In letteratura non vi sono esempi noti di clusterizzazione automatica della rete proposta senza l'arricchimento della stessa con ulteriori informazioni, il nostro lavoro ribadisce quindi la attuale difficoltà di trattare reti di questo tipo con metodi di clustering basati su distanze. 