---
title: "Human Disease Network Notebook"
output: html_notebook
---

```{r}
# set working directory
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

# source a set of functions
source("util.R")

# import libraries
libraries_list <- c("ggraph", "igraph", "dplyr", "readr", "DiagrammeR", "tidyverse", "Cairo", "networkD3", "CINNA", "scales")
import_libraries(libraries_list)
```

```{r}
# import graph
edges <- read.csv(
  "dataset/diseasome [Edges].csv",
  head = TRUE
)

nodes <- read.csv(
  "dataset/diseasome [Nodes].csv",
  head = TRUE
)

nodes <- nodes %>% select(-timeset)
edges <- edges %>% select(-timeset, -label)

graph <- graph.data.frame(edges, directed = TRUE, vertices = nodes)
# print(graph, e=TRUE, v=TRUE) ## IGRAPH 9af20f4 DNW- 1419 3926

ggraph(graph, layout = 'kk') +
  geom_edge_fan(colour = "gray") + 
  geom_node_point() +
  theme_graph(base_family = "Arial Narrow", base_size = 11) +
  ggtitle("Human Disease Network")
```

```{r}
ggsave("images/graph.pdf", device = "pdf", width = 30, height = 21, units = "cm")
```

```{r}
# similarities
ggplot(edges, aes(x = edges$Source, y = edges$Target, color = "red")) + 
  geom_point() + 
  labs(x = "Source") +
  labs(y = "Target") +
  ggtitle("Edges similarity")

# no isolated nodes
```
```{r}
ggsave("images/edge_similarity.pdf", device = "pdf", width = 30, height = 21, units = "cm")
```


## Centrality Analitycs

### Degree

```{r}
degree <- centr_degree(graph, mode = "all", normalized = TRUE)

ggplot(mapping=aes(degree$res)) + 
  geom_histogram(col="black", fill="red") + 
  scale_y_log10(labels = trans_format("log10", math_format(expr = 10^.x))) +
  scale_x_continuous(breaks = seq(0, 160, by = 20)) +
  labs(x = "degree") +
  labs(y = "frequency") +
  ggtitle("Degree histogram") +
  theme_bw()
```
```{r}
ggsave("images/degree_histogram.pdf", device = "pdf", width = 30, height = 21, units = "cm")
```

```{r}
ggraph(graph, layout = 'kk') +
  geom_edge_fan(colour = "gray") +
  geom_node_point(aes(size = degree$res)) + # FIXME: titla legend
  theme_graph(base_family = "Arial Narrow", base_size = 11) +
  ggtitle("Human Disease Network Degree Centrality") 

# node with the higest degree
V(graph)$label[degree$res==max(degree$res)] # "Colon cancer"
```
```{r}
ggsave("images/graph_degree.pdf", device = "pdf", width = 30, height = 21, units = "cm")
```

### Betweenness

```{r}
betweenness <- betweenness(graph, v = V(graph), directed = TRUE, normalized = TRUE)

ggplot(mapping=aes(betweenness)) + 
  geom_histogram(col="black", fill="red") + 
  scale_y_log10(labels = trans_format("log10", math_format(expr = 10^.x))) +
  scale_x_continuous(limits = c(0, 1)) +
  labs(x = "betweenness") +
  labs(y = "frequency") +
  ggtitle("Betweenness histogram") +
  theme_bw()
```
```{r}
ggsave("images/betweenness_histogram.pdf", device = "pdf", width = 30, height = 21, units = "cm")
```

```{r}
ggraph(graph, layout = 'kk') + 
  geom_edge_fan(colour = "gray") + 
  geom_node_point(aes(size = betweenness)) +
  theme_graph(base_family = "Arial Narrow", base_size = 11) +
  ggtitle("Human Disease Network Betweenness Centrality") 

# node with the higest betweenness
V(graph)$label[betweenness==max(betweenness)] # "Cardiomyopathy"
```
```{r}
ggsave("images/graph_betweenness.pdf", device = "pdf", width = 30, height = 21, units = "cm")
```

### Closeness

```{r}
closeness <- closeness(graph, v = V(graph), normalized = TRUE)

ggplot(mapping=aes(closeness)) + 
  geom_histogram(col="black", fill="red") + 
  scale_y_log10(labels = trans_format("log10", math_format(expr = 10^.x))) +
  scale_x_continuous(limits = c(0, 1)) +
  labs(x = "closeness") +
  labs(y = "frequency") +
  ggtitle("Closeness histogram") +
  theme_bw()
```
```{r}
ggsave("images/closeness_histogram.pdf", device = "pdf", width = 30, height = 21, units = "cm")
```

```{r}
ggraph(graph, layout = 'kk') + 
  geom_edge_fan(colour = "gray") + 
  geom_node_point(aes(size = closeness)) +
  theme_graph(base_family = "Arial Narrow", base_size = 11) +
  ggtitle("Human Disease Network Closeness Centrality") 

# node with the higest closeness
V(graph)$label[closeness==max(closeness)] # "Lipodystrophy"
```
```{r}
ggsave("images/graph_closeness.pdf", device = "pdf", width = 30, height = 21, units = "cm")
```

### Pagerank
```{r}
pagerank <- page_rank(graph, v = V(graph), directed = TRUE)

ggplot(mapping=aes(pagerank$vector)) + 
  geom_histogram(col="black", fill="red") + 
  scale_y_log10(labels = trans_format("log10", math_format(expr = 10^.x))) +
  #scale_x_continuous(limits = c(0, 1)) +
  labs(x = "pagerank") +
  labs(y = "frequency") +
  ggtitle("Pagerank histogram") +
  theme_bw()
```
```{r}
ggsave("images/pagerank_histogram.pdf", device = "pdf", width = 30, height = 21, units = "cm")
```

```{r}
ggraph(graph, layout = 'kk') +
  geom_edge_fan(colour = "gray") +
  geom_node_point(aes(size = pagerank$vector)) + #FIXME: legent title
  theme_graph(base_family = "Arial Narrow", base_size = 11) +
  ggtitle("Human Disease Network Pagerank Centrality") 

# node with the higest pagerank
V(graph)$label[pagerank$vector==max(pagerank$vector)] # "Colon cancer"
```
```{r}
ggsave("images/graph_pagerank.pdf", device = "pdf", width = 30, height = 21, units = "cm")
```

### Eigenvector

```{r}
eigen <- eigen_centrality(graph, directed = TRUE)

ggplot(mapping=aes(eigen$vector)) + 
  geom_histogram(col="black", fill="red") + 
  scale_y_log10(labels = trans_format("log10", math_format(expr = 10^.x))) +
  scale_x_continuous(limits = c(0, 1)) +
  labs(x = "eigen") +
  labs(y = "frequency") +
  ggtitle("Eigenvector histogram") +
  theme_bw()
```
```{r}
ggsave("images/eigen_histogram.pdf", device = "pdf", width = 30, height = 21, units = "cm")
```

```{r}
ggraph(graph, layout = 'kk') +
  geom_edge_fan(colour = "gray") +
  geom_node_point(aes(size = eigen$vector)) + # FIXME: label legend
  theme_graph(base_family = "Arial Narrow", base_size = 11) +
  ggtitle("Human Disease Network Eigenvector Centrality") 

# node with the higest eigen
V(graph)$label[eigen$vector==max(eigen$vector)] # "Colon cancer"
```
```{r}
ggsave("images/graph_eigen.pdf", device = "pdf", width = 30, height = 21, units = "cm")
```


## Community Detection

